AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-example-s3

  Sample SAM Template for sam-example-s3

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        OUTPUTBUCKET: example-write-00001234-naoki

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/example-lambda-role
      Layers:
        - !Ref MyLayerPyminizip
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref MyBucket
            Events: s3:ObjectCreated:*

  S3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref HelloWorldFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"
      SourceArn: !Sub arn:aws:s3:::example-read-00001234-naoki

  MyLayerPyminizip:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: "mylayer-pyminizip/"
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  MyBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: example-read-00001234-naoki

Outputs:
  MyFunctionArn:
    Value: !GetAtt HelloWorldFunction.Arn
